[project]
name = "graiax-fastapi"
version = "0.2.0"
description = "FastAPI for GraiaCommunity."
authors = [
    {name = "BlueGlassBlock", email = "blueglassblock@outlook.com"},
]
dependencies = [
    "graia-amnesia>=0.6.0",
    "fastapi>=0.70.0",
    "graia-saya>=0.0.16",
    "typing-extensions>=4.0.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}
[project.optional-dependencies]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black>=22.10.0",
    "isort>=5.10.1",
    "launart>=0.6.1",
    "uvicorn[standard]>=0.18.3",
    "coverage>=6.5.0",
    "pytest>=7.1.3",
    "pytest-asyncio>=0.19.0",
]
