name: Release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      release:
        description: Make Release
        required: true
        type: boolean
jobs:
  test:
    uses: ./.github/workflows/test.yml  # use the callable tests job to run tests
  publish:
    runs-on: ubuntu-latest
    needs: test # require tests to pass before deploy runs
    steps:
      - uses: actions/checkout@v3

      - name: Install PDM
        uses: pdm-project/setup-pdm@main

      - name: Build Package
        run: pdm build

      - name: Publish to PyPI
        if: ${{ github.event.inputs.release == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
